version: 2.0 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:latest # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          command: sudo npm install -g npm@latest
      - run:
          command: sudo npm install jasmine -g
      - run:
          command: sudo npm install -g grunt-cli
      - run:
          command: chmod 777 Gruntfile.js
      - run:
          command: npm test
